name: C/C++ CI

on:
  push:
    branches: [ "world120" ]
  pull_request:
    branches: [ "world120" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: lib install
      run: brew install boost libpng cmake libjpeg-turbo
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: tgz
      run: tar -czvf build.tgz build
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: upload
        path: build.tgz
