name: C/C++ CI

on:
  push:
    branches: [ "world120" ]
  pull_request:
    branches: [ "world120" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake .
    - name: make
      run: make
   
